import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/components/shared";
import { Header } from "@/components/shared/header";
import "../app/globals.css"

const inter = Inter({
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} antialiased`}>
      <body className="bg-neutral-50 text-black selection:bg-teal-300">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
